// <auto-generated />
using System;
using CoreCrud.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreCrud.Migrations
{
    [DbContext(typeof(CoreCrudContext))]
    partial class CoreCrudContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("CoreCrud.Models.LunchBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool?>("IsMicrowaveSafe");

                    b.Property<string>("LunchBoxName");

                    b.Property<int>("ManufacturerId");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("SoldDate");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("LunchBox");
                });

            modelBuilder.Entity("CoreCrud.Models.LunchBoxManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EstablishedOn");

                    b.Property<bool>("IsSellingOnline");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.Property<decimal>("SalesRevenue");

                    b.HasKey("Id");

                    b.ToTable("LunchBoxManufacturer");
                });

            modelBuilder.Entity("CoreCrud.Models.LunchBox", b =>
                {
                    b.HasOne("CoreCrud.Models.LunchBoxManufacturer", "Manufacturer")
                        .WithMany("LunchBoxes")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
